'use strict';
(function(){
  const icons={today:'<rect x="4" y="5" width="16" height="16" rx="3"/><path d="M8 3v4m8-4v4M4 11h16m-12 5 2 2 5-4"/>',sales:'<path d="M5 4h14v17l-3-2-4 2-4-2-3 2V4Z"/><path d="M9 9h6m-6 4h6"/>',inventory:'<path d="m3 7 9-4 9 4v10l-9 4-9-4V7Zm0 0 9 4 9-4M12 11v10M7 5l9 4"/>',money:'<rect x="3" y="5" width="18" height="15" rx="3"/><path d="M15 10h6v6h-6zM3 9h9"/>',distribution:'<path d="M3 6h11v12H3zM14 10h4l3 4v4h-7"/><circle cx="7" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>',dashboard:'<path d="M4 3v18h17M8 16v-4m5 4V7m5 9v-6"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>'};
  const guides={today:['Өнөөдрийн ажлаа харах','Борлуулалт бүртгэх товчоор шинэ борлуулалт хийнэ.','Авах мөнгө хэсгээс төлбөрийн үлдэгдлээ харна.','Бага үлдэгдэлтэй бараагаа шалгаж нөхөн авна.'],sales:['Борлуулалт хэрхэн бүртгэх вэ?','Худалдан авагчийн нэрийг сонгоно. Шинэ бол нэрийг нь бичнэ.','Бараагаа хайж, тоог оруулаад сагсанд нэмнэ.','Нийт дүн, төлбөрөө шалгаад борлуулалтаа хадгална.'],inventory:['Бараагаа хэрхэн бүртгэх вэ?','Барааны нэр, үнэ, нэгж болон эхний үлдэгдлийг оруулна.','Бараа ирэхэд орлого, гарахад зарлагыг бүртгэнэ.','Үлдэгдэл зөрвөл эрхтэй ажилтан тооллогоор шалгаж засна.'],money:['Авах мөнгөө хэрхэн хөтлөх вэ?','Харилцагчаа нэрээр нь хайна.','Мөнгө хүлээн авсан бол Төлөлт бүртгэх товчийг дарна.','Дүн, төлбөрийн аргаа шалгаж хадгална.'],distribution:['Хүргэлтээ хэрхэн хөтлөх вэ?','Борлуулалтаа сонгож жолоочид хүргэлт онооно.','Хүргэсэн болон буцаасан тоог бүртгэнэ.','Мөнгө авсан бол төлөлтийг тусад нь бүртгэнэ.'],more:['Бусад хэрэгтэй зүйл','Хүргэлт, тайлан, тохиргоонд эндээс орно.','Илгээгдээгүй бүртгэл байгаа эсэхийг шалгана.','Нөөцлөлт болон ажилтны эрхийг тохиргооноос удирдана.']};
  function enhance(){
    document.body.classList.toggle('daily-ui',!!document.getElementById('page-today'));
    document.querySelectorAll('.nav-btn[data-page]').forEach(b=>{const span=b.querySelector('span');if(span&&!span.querySelector('svg')&&icons[b.dataset.page])span.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+icons[b.dataset.page]+'</svg>';if(b.classList.contains('active'))b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
    for(const [name,steps] of Object.entries(guides)){const page=document.getElementById('page-'+name);if(!page||page.querySelector('.workspace-help'))continue;const details=document.createElement('details');details.className='workspace-help';const summary=document.createElement('summary');summary.textContent=steps[0];details.appendChild(summary);const content=document.createElement('div');content.className='help-content';const ol=document.createElement('ol');steps.slice(1).forEach(text=>{const li=document.createElement('li');li.textContent=text;ol.appendChild(li);});content.appendChild(ol);details.appendChild(content);page.querySelector('.page-head')?.after(details);}
  }
  function init(){
    const content=document.querySelector('.content');if(content){const tools=document.createElement('div');tools.className='workspace-tools';tools.innerHTML='<button type="button" data-text-size aria-pressed="false">Аа · Үсэг томруулах</button><a href="./contact.html" target="_blank" rel="noopener">Тусламж авах ↗</a>';if(document.body.classList.contains('large-text')){const b=tools.querySelector('button');b.setAttribute('aria-pressed','true');b.textContent='Аа · Хэвийн үсэг';}content.prepend(tools);}
    ['loginPassword','regPassword'].forEach(id=>{const input=document.getElementById(id);if(!input)return;const wrap=document.createElement('div');wrap.className='password-wrap';input.before(wrap);wrap.appendChild(input);const b=document.createElement('button');b.type='button';b.textContent='Харах';b.setAttribute('aria-label','Нууц үг харуулах');b.setAttribute('aria-pressed','false');b.setAttribute('aria-controls',id);b.addEventListener('click',()=>{const visible=input.type==='password';input.type=visible?'text':'password';b.textContent=visible?'Нуух':'Харах';b.setAttribute('aria-pressed',String(visible));b.setAttribute('aria-label',visible?'Нууц үг нуух':'Нууц үг харуулах');});wrap.appendChild(b);});
    document.querySelectorAll('.auth-tab').forEach(b=>{b.setAttribute('aria-pressed',String(b.classList.contains('active')));b.addEventListener('click',()=>{document.querySelectorAll('.auth-tab').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const p=document.querySelector('.auth-welcome');if(p)p.textContent=b.dataset.authTab==='register'?'Бизнесийнхээ үндсэн бүртгэлийг үүсгэнэ. Ажилтны эрхтэй бол менежерээсээ нэвтрэх нэрээ аваарай.':'Танай бүртгэлд тавтай морил.';});});
    document.querySelectorAll('.table-wrap').forEach(w=>{w.tabIndex=0;w.setAttribute('role','region');w.setAttribute('aria-label','Бүртгэлийн хүснэгт. Хажуу тийш гүйлгэж үзнэ.');const hint=document.createElement('p');hint.className='table-hint';hint.textContent='↔ Багануудыг хажуу тийш гүйлгэж үзнэ.';w.before(hint);});
    enhance();
  }
  const apply=applyPayload;applyPayload=function(...args){const result=apply(...args);enhance();return result;};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
