const {JSDOM,VirtualConsole}=require('jsdom');const fs=require('fs'),assert=require('node:assert/strict');
const source=fs.readFileSync('app-core.html','utf8');const inline=[...source.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');
const html=source.replace(/<script[\s\S]*?<\/script>/g,'');
const sale={id:'S1',customer:'Дэлгүүр',total:10000,returned:0,net:10000,paid:2000,remaining:8000,refundDue:0,date:new Date().toISOString(),dueDate:'2026-09-11',items:[{lineId:'L1',product:'Талх',quantity:10,unitPrice:1000,total:10000,returned:0}],payments:[],returns:[]};
const bootstrap={success:true,operationsVersion:1,token:'test',companyStatus:'Free',user:{username:'owner',fullName:'Менежер',role:'manager',company:'Туршилт'},company:{name:'Туршилт'},products:[{name:'Талх',price:1000,stock:100,unit:'ш',packName:'Хайрцаг',packSize:12,threshold:10}],customers:['Дэлгүүр'],warehouses:[{name:'Үндсэн агуулах'}],locations:[{name:'Үндсэн байршил'}],recentTransactions:[{saleId:'S1',product:'Талх',customer:'Дэлгүүр',quantity:10,unitPrice:1000,total:10000,date:new Date().toISOString(),paidAmount:2000,paymentType:'Зээл',clientId:'old'}],ads:[]};
const operations={version:1,asOf:new Date().toISOString(),today:'2026-09-11',todayTotal:10000,todayCount:1,sales:[sale],receivables:[sale],deliveries:[],cash:[],drivers:[{username:'driver',fullName:'Жолооч'}],batches:[],lowStock:[],pendingReturns:[]};
async function fixture(version=1){
 const errors=[],posts=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM(html,{url:'https://test.invalid/app.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;
 w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.confirm=()=>true;
 w.fetch=async(url,options={})=>{let data={...bootstrap,operationsVersion:version};const u=new URL(url);if(options.method==='POST'){const p=JSON.parse(options.body);posts.push(p);data=w.rejectAction===p.action?{success:false,message:'Үлдэгдэл хүрэлцэхгүй'}:{success:true,saleId:'S2',remainingStocks:{'Талх':76}};}else if(u.searchParams.get('action')==='operations')data=u.searchParams.get('saleId')?{success:true,sale}:{success:true,operations};else if(u.searchParams.get('action')==='module')data={success:true,inventoryMoves:[],visits:[],users:[],dashboard:{}};return {text:async()=>JSON.stringify(data)};};
 // One classic-script scope matches the real page and allows lexical state sharing.
 w.eval(inline+'\n'+fs.readFileSync('ads-config.js','utf8')+'\n'+fs.readFileSync('premium-ads.js','utf8')+'\n'+fs.readFileSync('operations-ui.js','utf8')+'\nwindow.testSetRole=r=>{state.session.user.role=r;renderAll();};window.testCart=()=>state.saleCart;window.testQueue=getQueue;window.testSaveQueue=saveQueue;window.testSync=syncOfflineQueue;window.testEnqueue=(...args)=>enqueueAction(...args);window.testUpdateProduct=()=>updateSaleProduct();window.testShowPage=p=>showPage(p);');
 await new Promise(r=>setTimeout(r,0));
 const doc=w.document;doc.querySelector('#loginUsername').value='owner';doc.querySelector('#loginPassword').value='password';doc.querySelector('#loginForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await new Promise(r=>setTimeout(r,20));
 return {dom,w,doc,posts,errors,settle:()=>new Promise(r=>setTimeout(r,20))};
}
(async()=>{
 let f=await fixture();assert.deepEqual(f.errors,[]);assert.equal(f.doc.querySelector('#page-today').classList.contains('active'),true);assert.ok(f.doc.querySelector('#ops-today').textContent.includes('10,000'));console.log('PASS DOM boots and opens daily work');
 f.doc.querySelector('#ops-today [data-ops="payment"]').click();await f.settle();assert.equal(f.doc.querySelector('#ops-dialog').open,true);f.doc.querySelector('[name="amount"]').value='1000';f.doc.querySelector('#ops-form').dispatchEvent(new f.w.Event('submit',{bubbles:true,cancelable:true}));await f.settle();assert.equal(f.posts.at(-1).action,'addPayment');assert.equal(f.doc.querySelector('#ops-dialog').open,false);console.log('PASS payment modal submits and refreshes');
 f.doc.querySelector('.mobile-nav [data-page="sales"]').click();f.doc.querySelector('#saleProduct').value='Талх';f.w.testUpdateProduct();f.doc.querySelector('#ops-sale-unit').value='pack';f.doc.querySelector('#ops-sale-unit').dispatchEvent(new f.w.Event('change'));f.doc.querySelector('#saleQty').value=2;f.doc.querySelector('#addSaleItemBtn').click();assert.equal(f.w.testCart()[0].quantity,24);assert.equal(f.w.testCart()[0].unitPrice,1000);console.log('PASS pack entry yields base-unit stock and price');
 f.doc.querySelector('.mobile-nav [data-page="more"]').click();f.doc.querySelector('#ops-more [data-value="distribution"]').click();f.doc.querySelector('[data-ops="dispatch"]').click();await f.settle();f.doc.querySelector('[name="address"]').value='Улаанбаатар';f.doc.querySelector('#ops-form').dispatchEvent(new f.w.Event('submit',{bubbles:true,cancelable:true}));await f.settle();assert.equal(f.posts.at(-1).action,'saveDelivery');console.log('PASS delivery assignment');
 f.doc.querySelector('.mobile-nav [data-page="money"]').click();f.doc.querySelector('#ops-money-search').value='none';f.doc.querySelector('#ops-money-search').dispatchEvent(new f.w.Event('input'));assert.equal(f.doc.querySelector('.ops-money-card').hidden,true);console.log('PASS receivables search');
 f.doc.querySelector('#ops-sale-paid').value='123';f.doc.querySelector('#ops-sale-due').value='2026-10-01';const queued=f.w.testEnqueue('addSale',{action:'addSale',customer:'Local',items:[{product:'Талх',quantity:1,unitPrice:1000}]});assert.equal(queued.payload.paidAmount,'123');assert.equal(f.doc.querySelector('#ops-sale-paid').value,'');f.w.rejectAction='addSale';await f.w.testSync(queued.id);assert.equal(f.w.testQueue().find(i=>i.id===queued.id).failed,true);console.log('PASS failed sale stays available and deposit does not leak to next sale');
 const before=f.posts.length;f.w.testSaveQueue([{id:'foreign',username:'different',company:'Туршилт',action:'addSale',payload:{action:'addSale'}}]);await f.w.testSync();assert.equal(f.posts.length,before);assert.equal(f.w.testQueue().length,1);console.log('PASS another employee queue is not submitted');
 f.w.rejectAction='';f.w.testSaveQueue([{id:'legacy',company:'Туршилт',action:'addSale',createdAt:new Date().toISOString(),payload:{action:'addSale',clientId:'legacy',customer:'Legacy',items:[{product:'Талх',quantity:1,unitPrice:1000}]}}]);f.w.testShowPage('more');await f.settle();f.doc.querySelector('[data-ops="claim-legacy-queue"]').click();await f.settle();assert.equal(f.posts.at(-1).clientId,'legacy');assert.equal(f.w.testQueue().length,0);console.log('PASS manager can recover a reviewed legacy queue item');
 f.w.testSetRole('driver');f.w.testShowPage('sales');assert.equal(f.doc.querySelector('#page-today').classList.contains('active'),true);assert.deepEqual(f.errors,[]);console.log('PASS role navigation');await f.settle();f.dom.window.close();
 f=await fixture(0);assert.equal(f.doc.querySelector('#page-today'),null);assert.equal(f.doc.querySelector('#page-sales').classList.contains('active'),true);assert.deepEqual(f.errors,[]);console.log('PASS old backend keeps original working UI');f.dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
