const {fixture}=require('./dom.test.cjs'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
(async()=>{
 let f=await fixture(1,1);assert.deepEqual(f.errors,[]);assert.ok(f.doc.querySelector('#ux-settings'));assert.ok(f.doc.querySelector('#ux-payment-details').open);console.log('PASS UX boots with visible payment method and settings');
 const state=f.w.testState;state.warehouses.push({name:'Салбар'});state.warehouseStocks.push({productId:'PRD-1',product:'Талх',warehouse:'Салбар',stock:2,available:2});f.w.testRender();f.doc.querySelector('#ux-sale-warehouse').value='Салбар';f.doc.querySelector('#saleProduct').value='Талх';f.w.testUpdateProduct();assert.ok(f.doc.querySelector('#saleStock').textContent.startsWith('2'));assert.throws(()=>f.w.uxValidateSale({customer:'Shop',items:[{product:'Талх',quantity:3,unitPrice:100}]}),/агуулахад/);console.log('PASS selected warehouse stock prevents overselling');
 state.recentTransactions=[{saleId:'paid',total:1000,paidAmount:0,quantity:1,product:'Талх',saleSummary:{remaining:0,paidAmount:1000,ledgerComplete:true,total:1000}}];assert.equal(f.w.testPayment(f.w.testGroups()[0]).label,'Төлсөн');console.log('PASS payment badge uses authoritative ledger');
 f.w.apiResults={uxRead:p=>({success:true,total:101,page:p.page,hasMore:p.page<2,rows:[{saleId:'PAGE-'+p.page,date:new Date().toISOString(),customer:'Page '+p.page,product:'Талх',quantity:1,total:100}]})};f.w.testShowPage('sales');await f.settle();assert.match(f.doc.querySelector('#ux-sales-count').textContent,/101/);f.doc.querySelector('[data-ux="sales-next"]').click();await f.settle();f.doc.querySelector('[data-ux="sales-next"]').click();await f.settle();assert.match(f.doc.querySelector('#ux-sales-count').textContent,/101–101/);assert.equal(f.doc.querySelector('[data-ux="sales-next"]').disabled,true);console.log('PASS sales pagination displays beyond 100');
 f.doc.querySelector('#ux-sale-warehouse').value='Үндсэн агуулах';f.doc.querySelector('#saleQty').value='2';f.doc.querySelector('#salePrice').value='1000';f.doc.querySelector('#ux-discount').value='50';f.doc.querySelector('#ux-discount-reason').value='Урамшуулал';f.doc.querySelector('#saleForm').dispatchEvent(new f.w.Event('input',{bubbles:true}));const key='datalinx-draft-v1:CMP-TEST:owner',draft=f.w.localStorage.getItem(key);assert.equal(JSON.parse(draft).fields['ux-discount'],'50');f.dom.window.close();f=await fixture(1,1,{[key]:draft});assert.equal(f.doc.querySelector('#ux-draft-banner').hidden,false);f.doc.querySelector('[data-ux="restore-draft"]').click();assert.equal(f.doc.querySelector('#saleQty').value,'2');assert.equal(f.doc.querySelector('#ux-discount').value,'50');f.w.uxClearDraft();assert.equal(f.w.localStorage.getItem(key),null);assert.equal(f.doc.querySelector('#ux-discount').value,'0');console.log('PASS draft survives reload with discount and clears after save');
 assert.equal(f.w.parseImportCsv('name,price\n'+Array.from({length:50},(_,i)=>'Бараа'+i+',100').join('\n')).length,50);assert.match(f.w.uxImportTable([{name:'<script>x</script>',price:100}]),/&lt;script&gt;/);assert.match(f.w.uxCsv(['name'],[{name:'=1+1'}]),/"'=1\+1"/);console.log('PASS 50 data rows plus header, escaped preview and safe CSV export');
 const imported=[];f.w.apiResults={inspectRequest:{success:true,status:'NotFound'},previewImport:{success:true},importData:p=>{imported.push(p);return {success:true}}};f.doc.querySelector('[data-reliable="import"]').click();const form=f.doc.querySelector('#ux-form'),submit=async()=>{form.dispatchEvent(new f.w.Event('submit',{bubbles:true,cancelable:true}));await f.settle();assert.equal(f.doc.querySelector('#ux-error').textContent,'');};form.elements.paste.value='Барааны нэр\tҮнэ\n'+Array.from({length:51},(_,i)=>'Бараа'+i+'\t100').join('\n');await submit();await submit();assert.equal(form.elements['map-0'].disabled,true);await submit();assert.deepEqual(imported.map(p=>p.rows.length),[50,1]);assert.notEqual(imported[0].clientId,imported[1].clientId);console.log('PASS mapped import previews then saves in stable 50-row batches');
 // Simulate committed batch with a lost response: inspect must skip it before preview.
 const text='Барааны нэр\tҮнэ\nRestored\t100',progress={signature:'products|'+text,mapping:['name','price'],next:0,ids:['already-done']};f.w.localStorage.setItem('datalinx-import:CMP-TEST:owner',JSON.stringify(progress));f.w.apiResults.inspectRequest={success:true,status:'Done'};const before=f.posts.filter(p=>p.action==='previewImport').length;f.doc.querySelector('[data-reliable="import"]').click();form.elements.paste.value=text;await submit();await submit();await submit();assert.equal(f.posts.filter(p=>p.action==='previewImport').length,before);assert.equal(imported.length,2);console.log('PASS interrupted committed import resumes without duplicate preview or write');
 assert.deepEqual(f.errors,[]);f.dom.window.close();
 f=await fixture(1,1,{['datalinx-draft-v1:OTHER:owner']:draft});assert.equal(f.doc.querySelector('#ux-draft-banner').hidden,true);assert.notEqual(f.doc.querySelector('#saleQty').value,'2');f.dom.window.close();console.log('PASS drafts remain isolated by company');
 f=await fixture(1,0);f.w.testState.warehouses.push({name:'Салбар'});f.w.testRender();f.doc.querySelector('#ux-sale-warehouse').value='Салбар';const oldPayload={customer:'Shop',items:[{product:'Талх',quantity:1,unitPrice:100}]};f.w.uxValidateSale(oldPayload);f.w.uxPrepareSale(oldPayload);assert.equal(oldPayload.warehouse,'Салбар');f.dom.window.close();console.log('PASS old backend preserves selected-warehouse sales until server update');
 require('child_process').execFileSync(process.execPath,['scripts/build-static.cjs']);const {JSDOM}=require('jsdom'),doc=new JSDOM(fs.readFileSync('dist/app.html','utf8')).window.document;for(const s of doc.querySelectorAll('script:not([src])'))new vm.Script(s.textContent);assert.ok(doc.querySelector('script[src*="experience-ui.js"]'));assert.ok(doc.querySelector('link[rel="manifest"]'));assert.equal(fs.existsSync('dist/UserExperienceService.gs'),false);console.log('PASS assembled production HTML has valid scripts and excludes backend');
})().catch(e=>{console.error(e);process.exitCode=1;});
